apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_APP_URL: "http://localhost:30080"
  CORS_ORIGINS: "http://localhost:30080,http://127.0.0.1:30080"
  LOG_LEVEL: "info"