apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  cors_origins: "http://frontend-service:3000,http://localhost:3000"
  port: "8000"
  next_public_backend_url: "http://backend-service:8000"
  next_public_api_base_url: "http://backend-service:8000"