apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: redpanda-cluster
spec:
  image: docker.vectorized.io/vectorized/redpanda:v22.2.3
  version: v22.2.3
  replicas: 1
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  configuration:
    rpcServer:
      address: 0.0.0.0
      port: 33145
    adminApi:
      address: 0.0.0.0
      port: 9644
    kafkaApi:
      - address: 0.0.0.0
        port: 9092
    pandaproxyApi:
      address: 0.0.0.0
        port: 8082
    developerMode: true
  licenseRef:
    secretKeyRef:
      name: redpanda-enterprise-license
      key: license